const PRODUCT_SPREADSHEET_ID = "1FYmDvp1KmFCBGe0MNHWP4m2YtRHtHdxqoOj0IOIJRyE";
const PRODUCT_SHEET_NAME = "シート1";

const PAYMENT_SPREADSHEET_ID = "1JAxaWaafrjVW5FSb1sFf_Q4sV3TcVYLUY0qGHR5acu0";
//const ORDER_SHEET_NAME = "order";
const ORDER_SHEET_NAME = "シート8";
// const SUBSCRIPTION_SHEET_NAME = "subscription";
const SUBSCRIPTION_SHEET_NAME = "シート8";

const DEBUG_SPREADSHEED_ID = "1u1Bqt13C-PLIssoxMQi_yt1rRZRTJZKH2O0iVqmrfg4";
const RAW_SHEET_NAME = "raw";
const POST_SHEET_NAME = "post";

const MISC_SPREADSHEET_ID = "1XDxu85GZ4Q8MNnCwxIB0NMBWKXLD0Tg_9xZoLFlRvM0";
const ORPHAN_PAYMENT_SHEET_NAME = "orphan-payment";
const ORDER_PRODUCT_SHEET_NAME = "order-product";
const HOOK_SHEET_NAME = "handled-hook";
const PLAN_PRODUCT_SHEET_NAME = "plan-product";


const SUBSCRIPTION_UPDATE_FROM = 8;
const SUBSCRIPTIOn_UPDATE_RANGE = 2;